name: CODE REVIEW REPORT
on:
  #pull_request:
  #    types: [opened, edited, reopened, synchronize]
  issue_comment:
jobs:
  pr_agent_report:
    if: (contains(github.event.comment.body, '/generate_report') && github.event.comment.user.login != 'nex-maximus') ||
        github.event_name == 'pull_request' && github.event.pull_request.user.login != 'nex-maximus'
    runs-on: [self-hosted, smart-devops-code-review]
    steps:
      - name: PR Agent report action step
        id: report
        uses: intel-innersource/frameworks.actions.maximus.genai-gpt/create-code-review-report@feature/genai_code_review_eval_release
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          USE_CUSTOM_MODEL: true
          CUSTOM_PROD_API_BASE: ${{ secrets.CUSTOM_PROD_API_BASE }}
          CUSTOM_PROD_API_KEY: ${{ secrets.CUSTOM_PROD_API_KEY }}
          GPT4128K_DEPLOY_NAME: ${{ secrets.GPT4128K_DEPLOY_NAME }}
          CUSTOM_API_VERSION: ${{ secrets.CUSTOM_API_VERSION }}
