name: OpenAPI Verify
on:
  push:
    paths:
      - 'api/openapi/**.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'api/openapi/**.yml'
  workflow_dispatch: {}

jobs:
  OpenAPI-Verify:
    name: Verify syntax and semantical correctness of API 
    container:
      image: amr-registry-pre.caas.intel.com/cloudburst-canyon/oapi-verify:1.2
    runs-on: gasp
    defaults:
      run:
        shell: sh
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.0.2

      - name: Verify OpenAPI Compliance
        run: |
          swagger-cli validate "${GITHUB_WORKSPACE}/api/openapi/dkam-api.yml"
          # TODO: Need to check if we can validate all openapi files in
          # the path or need to add separate line for each file. For now
          # we have only 1 file.
