apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onboarding-manager.fullname" . }}
  labels:
    {{- include "onboarding-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "onboarding-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "onboarding-manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: hooks-vol
          hostPath:
            path: "/opt/hook"
        - name: secrets-vol
          hostPath:
            path: {{ .Values.volumes.secret_path }}
        - name: kubeconfig-vol
          hostPath:
            path: {{ .Values.volumes.kube_config }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: secrets-vol
              mountPath: "/fdo-secrets"
            - name: hooks-vol
              mountPath: "/opt/hook"
            - name: kubeconfig-vol
              mountPath: "/kubecfg"
          env:
          - name: MGR_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ONBMGR_PORT
            value: {{ .Values.service.port }}
          - name: IAAS_ROOT_DIR
            value: {{ .Values.env.repo_dir }}
          ports:
            - name: grpc-port
              containerPort: {{ .Values.service.port }}
              protocol: TCP
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
