apiVersion: v1
kind: Service
metadata:
  name: onboarding-manager-service
  labels:
    {{- include "onboarding-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc-port
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "onboarding-manager.selectorLabels" . | nindent 4 }}
