apiVersion: "tinkerbell.org/v1alpha1"
kind: Template
metadata:
  name: fdostat-$TINKERBELL_CLIENT_UID
spec:
  data: |
    version: "0.1"
    name: fdostat_$TINKERBELL_CLIENT_UID
    global_timeout: 8000
    tasks:
      - name: "to-stat"
        worker: "{{.device_1}}"
        volumes:
          - /dev:/dev
          - /dev/console:/dev/console
          - /lib/firmware:/lib/firmware:ro
        actions:
          - name: "check-FDO-completed"
            image: quay.io/tinkerbell-actions/cexec:v1.0.0
            timeout: 90
            environment:
              BLOCK_DEVICE: {{ index .Hardware.Disks 0 }}$HOOKS_PARTITION
              FS_TYPE: ext4
              CHROOT: n
              DEFAULT_INTERPRETER: "/bin/sh -c"
              CMD_LINE: "cat /var/log/onboot/onboot.004-fdo.out.log"

