# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.SYS_OIE_DEVOPS_GITHUBAPI_TOKEN }}
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    registries:
      - github
    schedule:
      interval: daily
    open-pull-requests-limit: 2
    commit-message:
      prefix: "[gomod] "
