# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
version: 2
updates:
  # Go modules - separate block for each directory
  - package-ecosystem: "gomod"
    directory: "/onboarding-manager"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[gomod] "
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns: # Internal dependencies are update into separate PRs.
          - "*open-edge-platform*"
      internal-dependencies:
        patterns:
          - "*open-edge-platform*"

  - package-ecosystem: "gomod"
    directory: "/dkam"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[gomod] "
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns: # Internal dependencies are update into separate PRs.
          - "*open-edge-platform*"
      internal-dependencies:
        patterns:
          - "*open-edge-platform*"

  - package-ecosystem: "gomod"
    directory: "/tinker-actions"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[gomod] "
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns: # Internal dependencies are update into separate PRs.
          - "*open-edge-platform*"
      internal-dependencies:
        patterns:
          - "*open-edge-platform*"

  # Docker
  - package-ecosystem: "docker"
    directory: "/tinker-actions"  # Changed from "directories" to "directory"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[docker] "

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[gha] "
