# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: download-bkc-pkg-agents
  namespace: tink-system
data:
  entrypoint.sh: |-
    #!/usr/bin/env bash
    # This script is designed to download a cloud image file (.img) and then convert it to a .raw.gz file.
    # This is purpose built so non-raw cloud image files can be used with the "image2disk" action.
    # See https://artifacthub.io/packages/tbaction/tinkerbell-community/image2disk.
    set -euxo pipefail
    echo "nameserver 10.248.2.1" >> /etc/resolv.conf
    echo "nameserver 172.30.90.4" >> /etc/resolv.conf
    echo "nameserver 10.223.45.36" >> /etc/resolv.conf
    export http_proxy=http://proxy-dmz.intel.com:911
    export https_proxy=http://proxy-dmz.intel.com:912
    export no_proxy=localhost,.intel.com,devtools.intel.com,127.0.0.0/8,172.16.0.0/20,192.168.0.0/16,10.0.0.0/8
    if ! which pigz qemu-img &>/dev/null; then
      apk add --update pigz qemu-img wget bzip2 tar
    fi
    
    base_pkg_script_url=$1
    script_name=${base_pkg_script_url##*/}
    if [ -f $script_name ]; then
      rm $script_name
    fi
    wget --no-proxy $base_pkg_script_url
    cp $script_name $2/profile_and_agent_installer.sh

---
apiVersion: batch/v1
kind: Job
metadata:
  name: download-ubuntu-bkc-pkg-agents
  namespace: tink-system
spec:
  template:
    spec:
      containers:
      - name: download-ubuntu-bkc-pkg-agents
        image: bash:5.2.2
        command: ["/script/entrypoint.sh"]
        args: ["BKC_BASEPKG_URL", "/output","/repo","HOST_IP","/productuuid"]
        volumeMounts:
        - mountPath: /output
          name: hook-artifacts
        - mountPath: /script
          name: configmap-volume
        - mountPath: /repo
          name: code-repo
        - mountPath: /productuuid
          name: product-uuid
      restartPolicy: OnFailure
      volumes:
      - name: hook-artifacts
        hostPath:
          path: /opt/hook
          type: DirectoryOrCreate
      - name: code-repo
        hostPath:
          path: "CurrentRepoPath"
          type: DirectoryOrCreate
      - name: product-uuid
        hostPath:
          path: "/sys/class/dmi/id"
          type: DirectoryOrCreate
      - name: configmap-volume
        configMap:
          defaultMode: 0700
          name: download-bkc-pkg-agents
