// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: onboarding.proto

package onboardingmgr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NodeArtifactServiceNBClient is the client API for NodeArtifactServiceNB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeArtifactServiceNBClient interface {
	CreateNodes(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
}

type nodeArtifactServiceNBClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeArtifactServiceNBClient(cc grpc.ClientConnInterface) NodeArtifactServiceNBClient {
	return &nodeArtifactServiceNBClient{cc}
}

func (c *nodeArtifactServiceNBClient) CreateNodes(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, "/onboardingmgr.NodeArtifactServiceNB/CreateNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeArtifactServiceNBServer is the server API for NodeArtifactServiceNB service.
// All implementations should embed UnimplementedNodeArtifactServiceNBServer
// for forward compatibility
type NodeArtifactServiceNBServer interface {
	CreateNodes(context.Context, *NodeRequest) (*NodeResponse, error)
}

// UnimplementedNodeArtifactServiceNBServer should be embedded to have forward compatible implementations.
type UnimplementedNodeArtifactServiceNBServer struct {
}

func (UnimplementedNodeArtifactServiceNBServer) CreateNodes(context.Context, *NodeRequest) (*NodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNodes not implemented")
}

// UnsafeNodeArtifactServiceNBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeArtifactServiceNBServer will
// result in compilation errors.
type UnsafeNodeArtifactServiceNBServer interface {
	mustEmbedUnimplementedNodeArtifactServiceNBServer()
}

func RegisterNodeArtifactServiceNBServer(s grpc.ServiceRegistrar, srv NodeArtifactServiceNBServer) {
	s.RegisterService(&NodeArtifactServiceNB_ServiceDesc, srv)
}

func _NodeArtifactServiceNB_CreateNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeArtifactServiceNBServer).CreateNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onboardingmgr.NodeArtifactServiceNB/CreateNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeArtifactServiceNBServer).CreateNodes(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeArtifactServiceNB_ServiceDesc is the grpc.ServiceDesc for NodeArtifactServiceNB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeArtifactServiceNB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onboardingmgr.NodeArtifactServiceNB",
	HandlerType: (*NodeArtifactServiceNBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNodes",
			Handler:    _NodeArtifactServiceNB_CreateNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "onboarding.proto",
}

// NonInteractiveOnboardingServiceClient is the client API for NonInteractiveOnboardingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NonInteractiveOnboardingServiceClient interface {
	// OnboardNodeStream establishes a bidirectional stream between the EN and the OM
	// It allows EN to send stream requests and receive responses
	OnboardNodeStream(ctx context.Context, opts ...grpc.CallOption) (NonInteractiveOnboardingService_OnboardNodeStreamClient, error)
}

type nonInteractiveOnboardingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNonInteractiveOnboardingServiceClient(cc grpc.ClientConnInterface) NonInteractiveOnboardingServiceClient {
	return &nonInteractiveOnboardingServiceClient{cc}
}

func (c *nonInteractiveOnboardingServiceClient) OnboardNodeStream(ctx context.Context, opts ...grpc.CallOption) (NonInteractiveOnboardingService_OnboardNodeStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &NonInteractiveOnboardingService_ServiceDesc.Streams[0], "/onboardingmgr.NonInteractiveOnboardingService/OnboardNodeStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &nonInteractiveOnboardingServiceOnboardNodeStreamClient{stream}
	return x, nil
}

type NonInteractiveOnboardingService_OnboardNodeStreamClient interface {
	Send(*OnboardStreamRequest) error
	Recv() (*OnboardStreamResponse, error)
	grpc.ClientStream
}

type nonInteractiveOnboardingServiceOnboardNodeStreamClient struct {
	grpc.ClientStream
}

func (x *nonInteractiveOnboardingServiceOnboardNodeStreamClient) Send(m *OnboardStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nonInteractiveOnboardingServiceOnboardNodeStreamClient) Recv() (*OnboardStreamResponse, error) {
	m := new(OnboardStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NonInteractiveOnboardingServiceServer is the server API for NonInteractiveOnboardingService service.
// All implementations should embed UnimplementedNonInteractiveOnboardingServiceServer
// for forward compatibility
type NonInteractiveOnboardingServiceServer interface {
	// OnboardNodeStream establishes a bidirectional stream between the EN and the OM
	// It allows EN to send stream requests and receive responses
	OnboardNodeStream(NonInteractiveOnboardingService_OnboardNodeStreamServer) error
}

// UnimplementedNonInteractiveOnboardingServiceServer should be embedded to have forward compatible implementations.
type UnimplementedNonInteractiveOnboardingServiceServer struct {
}

func (UnimplementedNonInteractiveOnboardingServiceServer) OnboardNodeStream(NonInteractiveOnboardingService_OnboardNodeStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method OnboardNodeStream not implemented")
}

// UnsafeNonInteractiveOnboardingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NonInteractiveOnboardingServiceServer will
// result in compilation errors.
type UnsafeNonInteractiveOnboardingServiceServer interface {
	mustEmbedUnimplementedNonInteractiveOnboardingServiceServer()
}

func RegisterNonInteractiveOnboardingServiceServer(s grpc.ServiceRegistrar, srv NonInteractiveOnboardingServiceServer) {
	s.RegisterService(&NonInteractiveOnboardingService_ServiceDesc, srv)
}

func _NonInteractiveOnboardingService_OnboardNodeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NonInteractiveOnboardingServiceServer).OnboardNodeStream(&nonInteractiveOnboardingServiceOnboardNodeStreamServer{stream})
}

type NonInteractiveOnboardingService_OnboardNodeStreamServer interface {
	Send(*OnboardStreamResponse) error
	Recv() (*OnboardStreamRequest, error)
	grpc.ServerStream
}

type nonInteractiveOnboardingServiceOnboardNodeStreamServer struct {
	grpc.ServerStream
}

func (x *nonInteractiveOnboardingServiceOnboardNodeStreamServer) Send(m *OnboardStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nonInteractiveOnboardingServiceOnboardNodeStreamServer) Recv() (*OnboardStreamRequest, error) {
	m := new(OnboardStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NonInteractiveOnboardingService_ServiceDesc is the grpc.ServiceDesc for NonInteractiveOnboardingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NonInteractiveOnboardingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onboardingmgr.NonInteractiveOnboardingService",
	HandlerType: (*NonInteractiveOnboardingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnboardNodeStream",
			Handler:       _NonInteractiveOnboardingService_OnboardNodeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "onboarding.proto",
}
