// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: onboarding.proto

package onboardingmgr

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _onboarding_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on NodeRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NodeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NodeRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NodeRequestMultiError, or
// nil if none found.
func (m *NodeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *NodeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPayload() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, NodeRequestValidationError{
						field:  fmt.Sprintf("Payload[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, NodeRequestValidationError{
						field:  fmt.Sprintf("Payload[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return NodeRequestValidationError{
					field:  fmt.Sprintf("Payload[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return NodeRequestMultiError(errors)
	}

	return nil
}

// NodeRequestMultiError is an error wrapping multiple validation errors
// returned by NodeRequest.ValidateAll() if the designated constraints aren't met.
type NodeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NodeRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NodeRequestMultiError) AllErrors() []error { return m }

// NodeRequestValidationError is the validation error returned by
// NodeRequest.Validate if the designated constraints aren't met.
type NodeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NodeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NodeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NodeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NodeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NodeRequestValidationError) ErrorName() string { return "NodeRequestValidationError" }

// Error satisfies the builtin error interface
func (e NodeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNodeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NodeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NodeRequestValidationError{}

// Validate checks the field values on NodeResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NodeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NodeResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NodeResponseMultiError, or
// nil if none found.
func (m *NodeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *NodeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPayload() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, NodeResponseValidationError{
						field:  fmt.Sprintf("Payload[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, NodeResponseValidationError{
						field:  fmt.Sprintf("Payload[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return NodeResponseValidationError{
					field:  fmt.Sprintf("Payload[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for ProjectId

	if len(errors) > 0 {
		return NodeResponseMultiError(errors)
	}

	return nil
}

// NodeResponseMultiError is an error wrapping multiple validation errors
// returned by NodeResponse.ValidateAll() if the designated constraints aren't met.
type NodeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NodeResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NodeResponseMultiError) AllErrors() []error { return m }

// NodeResponseValidationError is the validation error returned by
// NodeResponse.Validate if the designated constraints aren't met.
type NodeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NodeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NodeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NodeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NodeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NodeResponseValidationError) ErrorName() string { return "NodeResponseValidationError" }

// Error satisfies the builtin error interface
func (e NodeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNodeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NodeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NodeResponseValidationError{}

// Validate checks the field values on NodeData with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NodeData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NodeData with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NodeDataMultiError, or nil
// if none found.
func (m *NodeData) ValidateAll() error {
	return m.validate(true)
}

func (m *NodeData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetHwdata() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, NodeDataValidationError{
						field:  fmt.Sprintf("Hwdata[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, NodeDataValidationError{
						field:  fmt.Sprintf("Hwdata[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return NodeDataValidationError{
					field:  fmt.Sprintf("Hwdata[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return NodeDataMultiError(errors)
	}

	return nil
}

// NodeDataMultiError is an error wrapping multiple validation errors returned
// by NodeData.ValidateAll() if the designated constraints aren't met.
type NodeDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NodeDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NodeDataMultiError) AllErrors() []error { return m }

// NodeDataValidationError is the validation error returned by
// NodeData.Validate if the designated constraints aren't met.
type NodeDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NodeDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NodeDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NodeDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NodeDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NodeDataValidationError) ErrorName() string { return "NodeDataValidationError" }

// Error satisfies the builtin error interface
func (e NodeDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNodeData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NodeDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NodeDataValidationError{}

// Validate checks the field values on HwData with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HwData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HwData with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in HwDataMultiError, or nil if none found.
func (m *HwData) ValidateAll() error {
	return m.validate(true)
}

func (m *HwData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUuid()); err != nil {
		err = HwDataValidationError{
			field:  "Uuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_HwData_Serialnum_Pattern.MatchString(m.GetSerialnum()) {
		err := HwDataValidationError{
			field:  "Serialnum",
			reason: "value does not match regex pattern \"^[A-Za-z0-9]{5,20}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_HwData_MacId_Pattern.MatchString(m.GetMacId()) {
		err := HwDataValidationError{
			field:  "MacId",
			reason: "value does not match regex pattern \"^([0-9a-fA-F]{2}([-:])){5}[0-9a-fA-F]{2}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_HwData_SutIp_Pattern.MatchString(m.GetSutIp()) {
		err := HwDataValidationError{
			field:  "SutIp",
			reason: "value does not match regex pattern \"^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return HwDataMultiError(errors)
	}

	return nil
}

func (m *HwData) _validateUuid(uuid string) error {
	if matched := _onboarding_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// HwDataMultiError is an error wrapping multiple validation errors returned by
// HwData.ValidateAll() if the designated constraints aren't met.
type HwDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HwDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HwDataMultiError) AllErrors() []error { return m }

// HwDataValidationError is the validation error returned by HwData.Validate if
// the designated constraints aren't met.
type HwDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HwDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HwDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HwDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HwDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HwDataValidationError) ErrorName() string { return "HwDataValidationError" }

// Error satisfies the builtin error interface
func (e HwDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHwData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HwDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HwDataValidationError{}

var _HwData_Serialnum_Pattern = regexp.MustCompile("^[A-Za-z0-9]{5,20}$")

var _HwData_MacId_Pattern = regexp.MustCompile("^([0-9a-fA-F]{2}([-:])){5}[0-9a-fA-F]{2}$")

var _HwData_SutIp_Pattern = regexp.MustCompile("^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$")

// Validate checks the field values on OnboardStreamRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OnboardStreamRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OnboardStreamRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OnboardStreamRequestMultiError, or nil if none found.
func (m *OnboardStreamRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *OnboardStreamRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUuid()); err != nil {
		err = OnboardStreamRequestValidationError{
			field:  "Uuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_OnboardStreamRequest_Serialnum_Pattern.MatchString(m.GetSerialnum()) {
		err := OnboardStreamRequestValidationError{
			field:  "Serialnum",
			reason: "value does not match regex pattern \"^[A-Za-z0-9]{5,20}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_OnboardStreamRequest_MacId_Pattern.MatchString(m.GetMacId()) {
		err := OnboardStreamRequestValidationError{
			field:  "MacId",
			reason: "value does not match regex pattern \"^([0-9a-fA-F]{2}([-:])){5}[0-9a-fA-F]{2}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_OnboardStreamRequest_HostIp_Pattern.MatchString(m.GetHostIp()) {
		err := OnboardStreamRequestValidationError{
			field:  "HostIp",
			reason: "value does not match regex pattern \"^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OnboardStreamRequestMultiError(errors)
	}

	return nil
}

func (m *OnboardStreamRequest) _validateUuid(uuid string) error {
	if matched := _onboarding_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// OnboardStreamRequestMultiError is an error wrapping multiple validation
// errors returned by OnboardStreamRequest.ValidateAll() if the designated
// constraints aren't met.
type OnboardStreamRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OnboardStreamRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OnboardStreamRequestMultiError) AllErrors() []error { return m }

// OnboardStreamRequestValidationError is the validation error returned by
// OnboardStreamRequest.Validate if the designated constraints aren't met.
type OnboardStreamRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OnboardStreamRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OnboardStreamRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OnboardStreamRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OnboardStreamRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OnboardStreamRequestValidationError) ErrorName() string {
	return "OnboardStreamRequestValidationError"
}

// Error satisfies the builtin error interface
func (e OnboardStreamRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOnboardStreamRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OnboardStreamRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OnboardStreamRequestValidationError{}

var _OnboardStreamRequest_Serialnum_Pattern = regexp.MustCompile("^[A-Za-z0-9]{5,20}$")

var _OnboardStreamRequest_MacId_Pattern = regexp.MustCompile("^([0-9a-fA-F]{2}([-:])){5}[0-9a-fA-F]{2}$")

var _OnboardStreamRequest_HostIp_Pattern = regexp.MustCompile("^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$")

// Validate checks the field values on OnboardStreamResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OnboardStreamResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OnboardStreamResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OnboardStreamResponseMultiError, or nil if none found.
func (m *OnboardStreamResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *OnboardStreamResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetStatus()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OnboardStreamResponseValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OnboardStreamResponseValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStatus()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OnboardStreamResponseValidationError{
				field:  "Status",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for NodeState

	// no validation rules for ClientId

	// no validation rules for ClientSecret

	// no validation rules for ProjectId

	if len(errors) > 0 {
		return OnboardStreamResponseMultiError(errors)
	}

	return nil
}

// OnboardStreamResponseMultiError is an error wrapping multiple validation
// errors returned by OnboardStreamResponse.ValidateAll() if the designated
// constraints aren't met.
type OnboardStreamResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OnboardStreamResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OnboardStreamResponseMultiError) AllErrors() []error { return m }

// OnboardStreamResponseValidationError is the validation error returned by
// OnboardStreamResponse.Validate if the designated constraints aren't met.
type OnboardStreamResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OnboardStreamResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OnboardStreamResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OnboardStreamResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OnboardStreamResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OnboardStreamResponseValidationError) ErrorName() string {
	return "OnboardStreamResponseValidationError"
}

// Error satisfies the builtin error interface
func (e OnboardStreamResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOnboardStreamResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OnboardStreamResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OnboardStreamResponseValidationError{}
