apiVersion: "tinkerbell.org/v1alpha1"
kind: Workflow
metadata:
  name: workflow-$TINKERBELL_CLIENT_UID
  namespace: tink-system
spec:
  templateRef: fdods-$TINKERBELL_CLIENT_UID
  hardwareRef: machine-$TINKERBELL_CLIENT_UID
  hardwareMap:
    device_1: $TINKERBELL_CLIENT_MAC
