# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel
kernel:
  image: quay.io/tinkerbell/hook-kernel:5.10.85-d1225df88208e5a732e820a182b75fb35c737bdd
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"

init:
  - linuxkit/init:144c9cee8aed9e30a16940f2bf1d3813883aceda
  # can't use the latest version of runc because it has a bug that prevents docker from starting containers properly.
  - linuxkit/runc:v0.8
  - linuxkit/containerd:d445de33c7f08470187b068d247b1c0dea240f0a
  - linuxkit/ca-certificates:c1c73ef590dffb6a0138cf758fe4a4305c9864f4

onboot:
  - name: sysctl
    image: linuxkit/sysctl:a88a50c104d538b58da5e1441f6f0b4b738f76a6

  - name: sysfs
    image: linuxkit/sysfs:5fd982d39ff7bec8e480c67a110acb2d3794c291

  - name: vlan
    image: linuxkit/ip:6cc44dd4e18ddb02de01bc4b34b5799971b6a7bf
    binds.add:
      - /etc/ip/vlan.sh:/etc/ip/vlan.sh
    command: ["/etc/ip/vlan.sh"]

  - name: dhcpcd
    image: linuxkit/dhcpcd:52d2c4df0311b182e99241cdc382ff726755c450
    command: ["/etc/ip/dhcp.sh", "true"]
    binds.add:
      - /var/lib/dhcpcd:/var/lib/dhcpcd
      - /run:/run
      - /etc/ip/dhcp.sh:/etc/ip/dhcp.sh
      - /dhcpcd.conf:/dhcpcd.conf
    runtime:
      mkdir:
        - /var/lib/dhcpcd

  - name: client_auth
    image: client_auth:latest
    capabilities:
      - all
    binds:
      - /dev:/dev
      - /dev/console:/dev/console
      - /dev/ttyS0:/dev/ttyS0
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/idp/server_cert.pem:/usr/local/share/ca-certificates/IDP_keyclock.crt
      - /var:/var:rshared,rbind
      - /dev/shm:/dev/shm
      - /etc/hook/env_config:/etc/hook/env_config
    rootfsPropagation: shared
    env:
      - CLIENT_AUTH_PRE_BIND=TRUE
      - KEYCLOAK_URL=update_idp_url
      - EXTRA_HOSTS=update_extra_hosts


services:
  - name: getty
    image: linuxkit/getty:76951a596aa5e0867a38e28f0b94d620e948e3e8
    binds.add:
      - /etc/profile.d/local.sh:/etc/profile.d/local.sh
      - /etc/motd:/etc/motd
    env:
      - INSECURE=true

  - name: rngd
    image: linuxkit/rngd:310c16ec5315bd07d4b8f5332cfa7dc5cbc7d368

  - name: dhcpcd
    image: linuxkit/dhcpcd:52d2c4df0311b182e99241cdc382ff726755c450
    command: ["/etc/ip/dhcp.sh", "false"]
    binds.add:
      - /var/lib/dhcpcd:/var/lib/dhcpcd
      - /run:/run
      - /etc/ip/dhcp.sh:/etc/ip/dhcp.sh
      - /dhcpcd.conf:/dhcpcd.conf
    runtime:
      mkdir:
        - /var/lib/dhcpcd

  - name: ntpd
    image: linuxkit/openntpd:d6c36ac367ed26a6eeffd8db78334d9f8041b038
    binds:
      - /var/run:/var/run

  - name: fluent-bit
    image: fluentbit:latest
    binds.add:
      - /etc/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/log:/var/log
    rootfsPropagation: shared

  - name: hook-docker
    image: quay.io/tinkerbell/hook-docker:latest
    capabilities:
      - all
    net: host
    pid: host
    mounts:
      - type: cgroup
        options: ["rw", "nosuid", "noexec", "nodev", "relatime"]
    binds:
      - /dev/console:/dev/console
      - /dev:/dev
      - /etc/resolv.conf:/etc/resolv.conf
      - /lib/modules:/lib/modules
      - /var/run/docker:/var/run
      - /var/run/images:/var/lib/docker
      - /var/run/worker:/worker
      - /dev/shm:/dev/shm
    runtime:
      mkdir:
        - /var/run/images
        - /var/run/docker
        - /var/run/worker

  - name: hook-bootkit
    image: quay.io/tinkerbell/hook-bootkit:latest
    capabilities:
      - all
    net: host
    mounts:
      - type: cgroup
        options: ["rw", "nosuid", "noexec", "nodev", "relatime"]
    binds:
      - /var/run/docker:/var/run
    runtime:
      mkdir:
        - /var/run/docker

  - name: caddy
    image: caddy_proxy:latest
    capabilities:
      - all
    binds.add:
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/idp/ca.pem:/usr/local/share/ca-certificates/ensp-orchestrator-ca.crt
      - /etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /dev/shm/idp_access_token:/dev/shm/idp_access_token
      - /dev/shm/release_token:/dev/shm/release_token
      - /etc/hook/env_config:/etc/hook/env_config

    # Intended docker variables to be populated from environment
    env:
      - tink_stack_svc=update_tink_stack_svc
      - tink_server_svc=update_tink_server_svc
      - onboarding_manager_svc=update_onboarding_manager_svc
      - release_svc=update_release_svc
      - logging_svc=update_logging_svc
      - fdo_manufacturer_svc=update_manufacturer_svc
      - fdo_owner_svc=update_owner_svc
      - oci_release_svc=update_oci_release_svc
      - EXTRA_HOSTS=update_extra_hosts

#dbg  - name: sshd
#dbg    image: linuxkit/sshd:666b4a1a323140aa1f332826164afba506abf597

files:
  - path: etc/profile.d/local.sh
    contents: |
      alias       docker='ctr -n services.linuxkit tasks exec --tty --exec-id cmd hook-docker docker'
      alias docker-shell='ctr -n services.linuxkit tasks exec --tty --exec-id shell hook-docker sh'
    mode: "0644"

  - path: etc/idp/ca.pem
    source: files/idp/ca.pem
    mode: "0644"

  - path: etc/idp/server_cert.pem
    source: files/idp/server_cert.pem
    mode: "0644"

  - path: etc/motd
    mode: "0644"
    contents: |
      Welcome to HookOS! Your Tinkerbell operating system installation environment.

      ██   ██  ██████   ██████  ██   ██  ██████  ███████
      ██   ██ ██    ██ ██    ██ ██  ██  ██    ██ ██
      ███████ ██    ██ ██    ██ █████   ██    ██ ███████
      ██   ██ ██    ██ ██    ██ ██  ██  ██    ██      ██
      ██   ██  ██████   ██████  ██   ██  ██████  ███████

      - Press `enter` to get a prompt.
      - Use `docker` commands to access the tink worker/agent container and workflow action containers.
      - Logs are located in the `/var/log/` directory.

  - path: etc/ip/vlan.sh
    source: "files/vlan.sh"
    mode: "0777"

  - path: etc/ip/dhcp.sh
    source: "files/dhcp.sh"
    mode: "0777"

  - path: dhcpcd.conf
    source: "files/dhcpcd.conf"
    mode: "0644"

  - path: /etc/fluent-bit/fluent-bit.conf
    source: "files/fluent-bit/fluent-bit.conf"
    mode: "0644"

  - path: etc/caddy/Caddyfile
    source: "files/caddy/Caddyfile"
    mode: "0644"

  - path: etc/hook/env_config
    contents: ""
    mode: "0644"

#dbg  - path: root/.ssh/authorized_keys
#dbg    source: ~/.ssh/id_rsa.pub
#dbg    mode: "0600"
#dbg    optional: true

trust:
  org:
    - linuxkit
    - library

