---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "2"
run:
  go: ""
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
  timeout: 10m
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
    html:
      path: out/golangci-lint_report.html
linters:
  disable:
    - revive
    - prealloc
    - errcheck
    - gosec
    - noctx
    - nolintlint
    - staticcheck
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - goprintffuncname
    - lll
    - misspell
    - mnd
    - nakedret
    - nilerr
    - nilnil
    - predeclared
    - tagliatelle
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
  settings:
    gomoddirectives:
      replace-local: true
      replace-allow-list:
        - github.com/open-edge-platform/infra-onboarding/dkam
    cyclop:
      max-complexity: 10
    misspell:
      locale: US
    lll:
      line-length: 130
      tab-width: 4
    funlen:
      lines: 100
      statements: 50
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
    nakedret:
      max-func-lines: 1
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
          xml: camel
          bson: camel
          avro: snake
          mapstructure: kebab
    depguard:
      rules:
        main:
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
            - github.com/open-edge-platform
            - github.com/stretchr/testify
            - github.com/grpc-ecosystem
            - entgo.io/ent
            - github.com/goccy/go-json
            - github.com/google
            - google.golang.org
            - github.com/lib/pq
            - github.com/mennanov/fmutils
            - github.com/labstack/echo
            - github.com/onosproject
            - github.com/open-policy-agent
            - github.com/pkg/errors
            - github.com/rs/zerolog
            - github.com/cenkalti/backoff
            - github.com/spf13
            - k8s.io
            - github.com/tinkerbell
            - github.com/Nerzal/gocloak
            - github.com/scylladb/gocqlx
            - sigs.k8s.io
            - github.com/prometheus
            - gopkg.in/yaml.v2
        test:
          files:
            - $test
          allow:
            - $gostd
            - github.com/open-edge-platform
            - github.com/stretchr/testify
            - github.com/goccy/go-json
            - github.com/google
            - google.golang.org
            - github.com/grpc-ecosystem
            - github.com/mennanov/fmutils
            - github.com/onosproject
            - github.com/rs/zerolog
            - k8s.io
            - github.com/tinkerbell
            - sigs.k8s.io
            - github.com/pkg/errors
            - gopkg.in/yaml.v2
            - gotest.tools
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/open-edge-platform)
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
  exclude:
    - Error return value of `.*Close` is not checked
    - Error return value of `.*Flush` is not checked
    - Error return value of `.*Write` is not checked
    - Error return value of `.*Stop` is not checked
    - Error return value of `.*Remove` is not checked
    - Error return value of `.*Unsetenv` is not checked
    - Error return value of `.*Setenv` is not checked
    - 'G104: Errors unhandled'
    - 'G304: Potential file inclusion via variable'
    - 'G602: slice index out of range'
    - 'directive.*is unused for linter'
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - noctx
        - nolintlint
  uniq-by-line: false
