---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "2"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    - dupl
    - errcheck

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  go: ""

linters-settings:
  cyclop:
    max-complexity: 10
  dupl:
    threshold: 100
  govet:
    enable:
      - shadow
  misspell:
    locale: US
  lll:
    line-length: 130
    tab-width: 4
  funlen:
    lines: 100
    statements: 50
  exhaustive:
    default-signifies-exhaustive: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/open-edge-platform)
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeExprCopy
      - rangeValCopy
  nakedret:
    max-func-lines: 1
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
        xml: camel
        bson: camel
        avro: snake
        mapstructure: kebab

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
  exclude:
    - 'Error return value of `.*\.Close` is not checked'
    - 'Error return value of `.*\.Flush` is not checked'
    - 'Error return value of `.*\.Write` is not checked'
    - 'Error return value of `.*\.Stop` is not checked'
    - 'Error return value of `.*\.RemoveAll` is not checked'
    - 'Error return value of `.*\.Remove` is not checked'
    - 'Error return value of `.*\.Setenv` is not checked'
    - 'Error return value of `.*\.Unsetenv` is not checked'
  exclude-rules:
  uniq-by-line: false

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
    html:
      path: out/golangci-lint_report.html
  sort-results: true
