// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/onboarding.proto

package onboardingmgrv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _onboarding_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on CreateNodesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateNodesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateNodesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateNodesRequestMultiError, or nil if none found.
func (m *CreateNodesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateNodesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPayload() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateNodesRequestValidationError{
						field:  fmt.Sprintf("Payload[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateNodesRequestValidationError{
						field:  fmt.Sprintf("Payload[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateNodesRequestValidationError{
					field:  fmt.Sprintf("Payload[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CreateNodesRequestMultiError(errors)
	}

	return nil
}

// CreateNodesRequestMultiError is an error wrapping multiple validation errors
// returned by CreateNodesRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateNodesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateNodesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateNodesRequestMultiError) AllErrors() []error { return m }

// CreateNodesRequestValidationError is the validation error returned by
// CreateNodesRequest.Validate if the designated constraints aren't met.
type CreateNodesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateNodesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateNodesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateNodesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateNodesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateNodesRequestValidationError) ErrorName() string {
	return "CreateNodesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateNodesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateNodesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateNodesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateNodesRequestValidationError{}

// Validate checks the field values on CreateNodesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateNodesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateNodesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateNodesResponseMultiError, or nil if none found.
func (m *CreateNodesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateNodesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPayload() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateNodesResponseValidationError{
						field:  fmt.Sprintf("Payload[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateNodesResponseValidationError{
						field:  fmt.Sprintf("Payload[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateNodesResponseValidationError{
					field:  fmt.Sprintf("Payload[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for ProjectId

	if len(errors) > 0 {
		return CreateNodesResponseMultiError(errors)
	}

	return nil
}

// CreateNodesResponseMultiError is an error wrapping multiple validation
// errors returned by CreateNodesResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateNodesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateNodesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateNodesResponseMultiError) AllErrors() []error { return m }

// CreateNodesResponseValidationError is the validation error returned by
// CreateNodesResponse.Validate if the designated constraints aren't met.
type CreateNodesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateNodesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateNodesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateNodesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateNodesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateNodesResponseValidationError) ErrorName() string {
	return "CreateNodesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateNodesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateNodesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateNodesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateNodesResponseValidationError{}

// Validate checks the field values on NodeData with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NodeData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NodeData with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NodeDataMultiError, or nil
// if none found.
func (m *NodeData) ValidateAll() error {
	return m.validate(true)
}

func (m *NodeData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetHwdata() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, NodeDataValidationError{
						field:  fmt.Sprintf("Hwdata[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, NodeDataValidationError{
						field:  fmt.Sprintf("Hwdata[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return NodeDataValidationError{
					field:  fmt.Sprintf("Hwdata[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return NodeDataMultiError(errors)
	}

	return nil
}

// NodeDataMultiError is an error wrapping multiple validation errors returned
// by NodeData.ValidateAll() if the designated constraints aren't met.
type NodeDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NodeDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NodeDataMultiError) AllErrors() []error { return m }

// NodeDataValidationError is the validation error returned by
// NodeData.Validate if the designated constraints aren't met.
type NodeDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NodeDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NodeDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NodeDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NodeDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NodeDataValidationError) ErrorName() string { return "NodeDataValidationError" }

// Error satisfies the builtin error interface
func (e NodeDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNodeData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NodeDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NodeDataValidationError{}

// Validate checks the field values on HwData with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HwData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HwData with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in HwDataMultiError, or nil if none found.
func (m *HwData) ValidateAll() error {
	return m.validate(true)
}

func (m *HwData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUuid()); err != nil {
		err = HwDataValidationError{
			field:  "Uuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_HwData_Serialnum_Pattern.MatchString(m.GetSerialnum()) {
		err := HwDataValidationError{
			field:  "Serialnum",
			reason: "value does not match regex pattern \"^[A-Za-z0-9]{5,20}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_HwData_MacId_Pattern.MatchString(m.GetMacId()) {
		err := HwDataValidationError{
			field:  "MacId",
			reason: "value does not match regex pattern \"^([0-9a-fA-F]{2}([-:])){5}[0-9a-fA-F]{2}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_HwData_SutIp_Pattern.MatchString(m.GetSutIp()) {
		err := HwDataValidationError{
			field:  "SutIp",
			reason: "value does not match regex pattern \"^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return HwDataMultiError(errors)
	}

	return nil
}

func (m *HwData) _validateUuid(uuid string) error {
	if matched := _onboarding_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// HwDataMultiError is an error wrapping multiple validation errors returned by
// HwData.ValidateAll() if the designated constraints aren't met.
type HwDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HwDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HwDataMultiError) AllErrors() []error { return m }

// HwDataValidationError is the validation error returned by HwData.Validate if
// the designated constraints aren't met.
type HwDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HwDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HwDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HwDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HwDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HwDataValidationError) ErrorName() string { return "HwDataValidationError" }

// Error satisfies the builtin error interface
func (e HwDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHwData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HwDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HwDataValidationError{}

var _HwData_Serialnum_Pattern = regexp.MustCompile("^[A-Za-z0-9]{5,20}$")

var _HwData_MacId_Pattern = regexp.MustCompile("^([0-9a-fA-F]{2}([-:])){5}[0-9a-fA-F]{2}$")

var _HwData_SutIp_Pattern = regexp.MustCompile("^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$")

// Validate checks the field values on OnboardNodeStreamRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OnboardNodeStreamRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OnboardNodeStreamRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OnboardNodeStreamRequestMultiError, or nil if none found.
func (m *OnboardNodeStreamRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *OnboardNodeStreamRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUuid()); err != nil {
		err = OnboardNodeStreamRequestValidationError{
			field:  "Uuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_OnboardNodeStreamRequest_Serialnum_Pattern.MatchString(m.GetSerialnum()) {
		err := OnboardNodeStreamRequestValidationError{
			field:  "Serialnum",
			reason: "value does not match regex pattern \"^[A-Za-z0-9]{5,20}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_OnboardNodeStreamRequest_MacId_Pattern.MatchString(m.GetMacId()) {
		err := OnboardNodeStreamRequestValidationError{
			field:  "MacId",
			reason: "value does not match regex pattern \"^([0-9a-fA-F]{2}([-:])){5}[0-9a-fA-F]{2}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_OnboardNodeStreamRequest_HostIp_Pattern.MatchString(m.GetHostIp()) {
		err := OnboardNodeStreamRequestValidationError{
			field:  "HostIp",
			reason: "value does not match regex pattern \"^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OnboardNodeStreamRequestMultiError(errors)
	}

	return nil
}

func (m *OnboardNodeStreamRequest) _validateUuid(uuid string) error {
	if matched := _onboarding_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// OnboardNodeStreamRequestMultiError is an error wrapping multiple validation
// errors returned by OnboardNodeStreamRequest.ValidateAll() if the designated
// constraints aren't met.
type OnboardNodeStreamRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OnboardNodeStreamRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OnboardNodeStreamRequestMultiError) AllErrors() []error { return m }

// OnboardNodeStreamRequestValidationError is the validation error returned by
// OnboardNodeStreamRequest.Validate if the designated constraints aren't met.
type OnboardNodeStreamRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OnboardNodeStreamRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OnboardNodeStreamRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OnboardNodeStreamRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OnboardNodeStreamRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OnboardNodeStreamRequestValidationError) ErrorName() string {
	return "OnboardNodeStreamRequestValidationError"
}

// Error satisfies the builtin error interface
func (e OnboardNodeStreamRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOnboardNodeStreamRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OnboardNodeStreamRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OnboardNodeStreamRequestValidationError{}

var _OnboardNodeStreamRequest_Serialnum_Pattern = regexp.MustCompile("^[A-Za-z0-9]{5,20}$")

var _OnboardNodeStreamRequest_MacId_Pattern = regexp.MustCompile("^([0-9a-fA-F]{2}([-:])){5}[0-9a-fA-F]{2}$")

var _OnboardNodeStreamRequest_HostIp_Pattern = regexp.MustCompile("^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$")

// Validate checks the field values on OnboardNodeStreamResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OnboardNodeStreamResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OnboardNodeStreamResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OnboardNodeStreamResponseMultiError, or nil if none found.
func (m *OnboardNodeStreamResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *OnboardNodeStreamResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetStatus()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OnboardNodeStreamResponseValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OnboardNodeStreamResponseValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStatus()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OnboardNodeStreamResponseValidationError{
				field:  "Status",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for NodeState

	// no validation rules for ClientId

	// no validation rules for ClientSecret

	// no validation rules for ProjectId

	if len(errors) > 0 {
		return OnboardNodeStreamResponseMultiError(errors)
	}

	return nil
}

// OnboardNodeStreamResponseMultiError is an error wrapping multiple validation
// errors returned by OnboardNodeStreamResponse.ValidateAll() if the
// designated constraints aren't met.
type OnboardNodeStreamResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OnboardNodeStreamResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OnboardNodeStreamResponseMultiError) AllErrors() []error { return m }

// OnboardNodeStreamResponseValidationError is the validation error returned by
// OnboardNodeStreamResponse.Validate if the designated constraints aren't met.
type OnboardNodeStreamResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OnboardNodeStreamResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OnboardNodeStreamResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OnboardNodeStreamResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OnboardNodeStreamResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OnboardNodeStreamResponseValidationError) ErrorName() string {
	return "OnboardNodeStreamResponseValidationError"
}

// Error satisfies the builtin error interface
func (e OnboardNodeStreamResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOnboardNodeStreamResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OnboardNodeStreamResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OnboardNodeStreamResponseValidationError{}
