apiVersion: "tinkerbell.org/v1alpha1"
kind: Template
metadata:
  name: fdodi-$TINKERBELL_CLIENT_UID
spec:
  data: |
    version: "0.1"
    name: fdoDi-$TINKERBELL_CLIENT_UID
    global_timeout: 8000
    tasks:
      - name: "fdo-di-tsks"
        worker: "{{.device_1}}"
        volumes:
          - /dev:/dev
          - /dev/console:/dev/console
          - /lib/firmware:/lib/firmware:ro
        actions:
          - name: "create-partiion"
            image: docker.io/edgeiaas/part-create-action:v0.1
            timeout: 300
            environment:
              BLOCK_DEVICE: $DISK_DEVICE
              PARTITION_SZ: "500MB"
              PARTITION_WIPE: true
          - name: "run-fdo"
            image: docker.io/edgeiaas/fdoclient-action:v0.2
            timeout: 400
            environment:
              DATA_PARTITION_LBL: "CREDS"
              FDO_RUN_TYPE: "di"
              FDO_MFGIP: "$PROVISIONER_HOST_IP"
              FDO_MPORT: 8038
              DEVICE_SERIAL: "$TINKERBELL_DEV_SERIAL"
              TYPE: "CLIENT-SDK-TPM"
              FDO_TLS: "https"

