# Default values for fdo-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mariadb
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "10.6.14"

path:
  ca_cert: "/home/<USER>/.fdo-secrets/db/secrets/ca-cert.pem"
  server_cert: "/home/<USER>/.fdo-secrets/db/secrets/server-cert.pem"
  server_key: "/home/<USER>/.fdo-secrets/db/secrets/server-key.pem"
  db_password: "/home/<USER>/.fdo-secrets/db/secrets/db_password.txt"
  app_data: "/home/<USER>/.fdo-secrets/db/app-data"
  custom: "/home/<USER>/.fdo-secrets/db/custom"

hostNetwork: true

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: Exists
