#!/bin/sh

set -e

run() {
	echo "Starting Nginx..."

	envsubst '$BOOTS_SERVICE_URL' \
            </template/discover.php \
            >/usr/share/nginx/html/discover.php

	envsubst '$BOOTS_SERVICE_URL' \
            </template/chain.php \
            >/usr/share/nginx/html/chain.php
    
    cp /template/index.php /usr/share/nginx/html/

	php-fpm81 && chmod 777 /var/run/php/php81-fpm.sock && chmod 755 /usr/share/nginx/html/* && nginx -g 'daemon off;'
}

run
