#!/bin/sh

set -e

run() {
	echo "Starting Nginx..."

	echo "$(cat /template/index1.php)" > /usr/share/nginx/html/index.php

	echo "$(cat /template/discover1.php)" | sed "s/\$BOOTS_SERVICE_URL/$BOOTS_SERVICE_URL/g" >/usr/share/nginx/html/discover.php

	echo "$(cat /template/chain1.php)" | sed "s/\$BOOTS_SERVICE_URL/$BOOTS_SERVICE_URL/g" >/usr/share/nginx/html/chain.php

    php-fpm81 && nginx -g 'daemon off;'
}

run
