---
apiVersion: v1
kind: ConfigMap
metadata:
  name: download-image
data:
  entrypoint.sh: |-
    #!/usr/bin/env bash
    # This script is designed to download a cloud image file (.img) and then convert it to a .raw.gz file.
    # This is purpose built so non-raw cloud image files can be used with the "image2disk" action.
    # See https://artifacthub.io/packages/tbaction/tinkerbell-community/image2disk.
    set -euxo pipefail
    echo "nameserver 10.248.2.1" >> /etc/resolv.conf
    echo "nameserver 172.30.90.4" >> /etc/resolv.conf
    echo "nameserver 10.223.45.36" >> /etc/resolv.conf
    export http_proxy=http://proxy-dmz.intel.com:911
    export https_proxy=http://proxy-dmz.intel.com:912
    export no_proxy=localhost,.intel.com,127.0.0.0/8,172.16.0.0/20,192.168.0.0/16,10.0.0.0/8
    if ! which pigz qemu-img &>/dev/null; then
      apk add --update pigz qemu-img wget
    fi
    image_url=$1
    file=$2/${image_url##*/}
    file=${file%.*}.raw.gz
    if [[ ! -f "$file" ]]; then
      wget "$image_url" -O image1.img
      qemu-img convert -O raw image1.img image1.raw
      pigz <image1.raw >"$file"
      rm -f image1.img image1.raw
    fi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: download-ubuntu-focal
spec:
  template:
    spec:
      containers:
        - name: download-ubuntu-focal
          image: bash:5.2.2
          command: ["/script/entrypoint.sh"]
          args:
            [
              "https://cloud-images.ubuntu.com/daily/server/focal/current/focal-server-cloudimg-amd64.img",
              "/output",
            ]
          volumeMounts:
            - mountPath: /output
              name: hook-artifacts
            - mountPath: /script
              name: configmap-volume
      restartPolicy: OnFailure
      volumes:
        - name: hook-artifacts
          hostPath:
            path: /opt/hook
            type: DirectoryOrCreate
        - name: configmap-volume
          configMap:
            defaultMode: 0700
            name: download-image
