// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: dkammgr/v1/dkam.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetENProfileRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetENProfileRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetENProfileRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetENProfileRequestMultiError, or nil if none found.
func (m *GetENProfileRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetENProfileRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProfileName

	// no validation rules for Platform

	// no validation rules for RepoUrl

	// no validation rules for Sha256

	// no validation rules for InstalledPackages

	// no validation rules for KernelCommand

	// no validation rules for OsType

	if len(errors) > 0 {
		return GetENProfileRequestMultiError(errors)
	}

	return nil
}

// GetENProfileRequestMultiError is an error wrapping multiple validation
// errors returned by GetENProfileRequest.ValidateAll() if the designated
// constraints aren't met.
type GetENProfileRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetENProfileRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetENProfileRequestMultiError) AllErrors() []error { return m }

// GetENProfileRequestValidationError is the validation error returned by
// GetENProfileRequest.Validate if the designated constraints aren't met.
type GetENProfileRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetENProfileRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetENProfileRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetENProfileRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetENProfileRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetENProfileRequestValidationError) ErrorName() string {
	return "GetENProfileRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetENProfileRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetENProfileRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetENProfileRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetENProfileRequestValidationError{}

// Validate checks the field values on GetENProfileResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetENProfileResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetENProfileResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetENProfileResponseMultiError, or nil if none found.
func (m *GetENProfileResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetENProfileResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OsUrl

	// no validation rules for OverlayscriptUrl

	// no validation rules for TinkActionVersion

	// no validation rules for StatusCode

	// no validation rules for StatusMsg

	// no validation rules for OsImageSha256

	if len(errors) > 0 {
		return GetENProfileResponseMultiError(errors)
	}

	return nil
}

// GetENProfileResponseMultiError is an error wrapping multiple validation
// errors returned by GetENProfileResponse.ValidateAll() if the designated
// constraints aren't met.
type GetENProfileResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetENProfileResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetENProfileResponseMultiError) AllErrors() []error { return m }

// GetENProfileResponseValidationError is the validation error returned by
// GetENProfileResponse.Validate if the designated constraints aren't met.
type GetENProfileResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetENProfileResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetENProfileResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetENProfileResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetENProfileResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetENProfileResponseValidationError) ErrorName() string {
	return "GetENProfileResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetENProfileResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetENProfileResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetENProfileResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetENProfileResponseValidationError{}
