// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: dkammgr/v1/dkam.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetArtifactsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetArtifactsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArtifactsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetArtifactsRequestMultiError, or nil if none found.
func (m *GetArtifactsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArtifactsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProfileName

	// no validation rules for Platform

	if len(errors) > 0 {
		return GetArtifactsRequestMultiError(errors)
	}

	return nil
}

// GetArtifactsRequestMultiError is an error wrapping multiple validation
// errors returned by GetArtifactsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetArtifactsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArtifactsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArtifactsRequestMultiError) AllErrors() []error { return m }

// GetArtifactsRequestValidationError is the validation error returned by
// GetArtifactsRequest.Validate if the designated constraints aren't met.
type GetArtifactsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArtifactsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArtifactsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArtifactsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArtifactsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArtifactsRequestValidationError) ErrorName() string {
	return "GetArtifactsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetArtifactsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArtifactsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArtifactsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArtifactsRequestValidationError{}

// Validate checks the field values on GetArtifactsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetArtifactsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArtifactsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetArtifactsResponseMultiError, or nil if none found.
func (m *GetArtifactsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArtifactsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OsUrl

	// no validation rules for OverlayscriptUrl

	// no validation rules for TinkActionVersion

	// no validation rules for StatusCode

	if len(errors) > 0 {
		return GetArtifactsResponseMultiError(errors)
	}

	return nil
}

// GetArtifactsResponseMultiError is an error wrapping multiple validation
// errors returned by GetArtifactsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetArtifactsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArtifactsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArtifactsResponseMultiError) AllErrors() []error { return m }

// GetArtifactsResponseValidationError is the validation error returned by
// GetArtifactsResponse.Validate if the designated constraints aren't met.
type GetArtifactsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArtifactsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArtifactsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArtifactsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArtifactsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArtifactsResponseValidationError) ErrorName() string {
	return "GetArtifactsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetArtifactsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArtifactsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArtifactsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArtifactsResponseValidationError{}
