// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: onboarding_eb.proto

package provisioningproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OnBoardingEBClient is the client API for OnBoardingEB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OnBoardingEBClient interface {
	// Initialize connection with node
	StartOnboarding(ctx context.Context, in *OnboardingRequest, opts ...grpc.CallOption) (*OnboardingResponse, error)
}

type onBoardingEBClient struct {
	cc grpc.ClientConnInterface
}

func NewOnBoardingEBClient(cc grpc.ClientConnInterface) OnBoardingEBClient {
	return &onBoardingEBClient{cc}
}

func (c *onBoardingEBClient) StartOnboarding(ctx context.Context, in *OnboardingRequest, opts ...grpc.CallOption) (*OnboardingResponse, error) {
	out := new(OnboardingResponse)
	err := c.cc.Invoke(ctx, "/infrastructure.edge.iaas.platform.onboardingmgr.OnBoardingEB/StartOnboarding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnBoardingEBServer is the server API for OnBoardingEB service.
// All implementations must embed UnimplementedOnBoardingEBServer
// for forward compatibility
type OnBoardingEBServer interface {
	// Initialize connection with node
	StartOnboarding(context.Context, *OnboardingRequest) (*OnboardingResponse, error)
	mustEmbedUnimplementedOnBoardingEBServer()
}

// UnimplementedOnBoardingEBServer must be embedded to have forward compatible implementations.
type UnimplementedOnBoardingEBServer struct {
}

func (UnimplementedOnBoardingEBServer) StartOnboarding(context.Context, *OnboardingRequest) (*OnboardingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartOnboarding not implemented")
}
func (UnimplementedOnBoardingEBServer) mustEmbedUnimplementedOnBoardingEBServer() {}

// UnsafeOnBoardingEBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnBoardingEBServer will
// result in compilation errors.
type UnsafeOnBoardingEBServer interface {
	mustEmbedUnimplementedOnBoardingEBServer()
}

func RegisterOnBoardingEBServer(s grpc.ServiceRegistrar, srv OnBoardingEBServer) {
	s.RegisterService(&OnBoardingEB_ServiceDesc, srv)
}

func _OnBoardingEB_StartOnboarding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnboardingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnBoardingEBServer).StartOnboarding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infrastructure.edge.iaas.platform.onboardingmgr.OnBoardingEB/StartOnboarding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnBoardingEBServer).StartOnboarding(ctx, req.(*OnboardingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OnBoardingEB_ServiceDesc is the grpc.ServiceDesc for OnBoardingEB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OnBoardingEB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infrastructure.edge.iaas.platform.onboardingmgr.OnBoardingEB",
	HandlerType: (*OnBoardingEBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartOnboarding",
			Handler:    _OnBoardingEB_StartOnboarding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "onboarding_eb.proto",
}
