# SPDX-FileCopyrightText: (C) 2022 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mi-dkam.fullname" . }}
  labels:
    {{- include "mi-dkam.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "mi-dkam.selectorLabels" . | nindent 4 }}
