name: CODE REVIEW REPORT
on:
  #pull_request:
  #    types: [opened, edited, reopened, synchronize]
  issue_comment:
jobs:
  pr_agent_report:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ai-review') && (contains(github.event.comment.body, '/generate_report') && github.event.comment.user.login != 'nex-maximus') || (github.event_name == 'pull_request' && github.event.pull_request.user.login != 'nex-maximus') }}
    runs-on: ['innersource.prod.amr.dind']
    container: 
      image: gar-registry.caas.intel.com/maximus/smartdevops:genai-stable
      options: --pull always
    steps:
      - name: PR Agent report action step
        id: report
        # uses: intel-innersource/frameworks.actions.maximus.genai-gpt/create-code-review-report@feature/genai_code_review_eval_release
        run: |
          . /genai_agent/genai_env/bin/activate && /genai_agent/get_pr_eval_report.sh
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_ACTION.AUTO_REVIEW: true
          GITHUB_ACTION.AUTO_DESCRIBE: true
          GITHUB_ACTION.UPDATE_TITLE: false
          PR_NUMBER: ${{ github.event.number }}
          API_KEY: ${{ secrets.API_KEY }}
          API_BASE: ${{ secrets.API_BASE }}
          STABLE_API_VERSION: ${{ secrets.STABLE_API_VERSION }}
          PREVIEW_API_VERSION: ${{ secrets.PREVIEW_API_VERSION }}
          DEPLOY_NAME: ${{ secrets.DEPLOY_NAME }}
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

