---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Lint forbidden words

on:
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:

jobs:
  lint-forbidden-words:
    name: Lint Forbidden Words
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run lint
        uses: intel-tiber/orch-utils/.github/actions/lint-forbidden-words@main
        with:
          fail_on_match: "false"