---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge Pa Server

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - "pa-server/**"
  workflow_dispatch:

jobs:
  post-merge-pipeline:
    uses: intel-tiber/orch-ci/.github/workflows/post-merge.yml@main
    with:
      run_security_scans: true
      run_version_check: true
      run_dep_version_check: true
      run_build: true
      run_docker_build: true
      run_docker_push: true
      run_version_tag: true
      run_artifact: false
      prefix_tag_separator: "/"
      project_folder: "pa-server"
      orch_ci_repo_ref: "0.0.2"
    secrets: inherit
