---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Lint root directory

on:
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - "*"
      - ".github/**"
      - "LICENSES/**"
      - ".reuse/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MARKDOWNLINT_CLI_VER: 0.44.0

jobs:
  root-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v43.0
        with:
          node-version: "18"
      - run: |
          npm install -g \
          "markdownlint-cli@${{ env.MARKDOWNLINT_CLI_VER }}"
      - uses: actions/setup-python@v5.5.0
        id: setup_python
        with:
          python-version: "3.13"
      - name: Restore cached virtualenv
        uses: actions/cache@v4.2.3
          with:
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          path: venv_infra

      - name: Run mdlint
        run: make mdlint
      - name: Run license check
        run: make license
